project:
  type: website
  output-dir: docs

website:
  title: "Vishruth Veerendranath"
  favicon: pic_new.jpg
  twitter-card: true
  navbar:
    background: primary
    right:
      - publications.qmd
      - experience.qmd
      - text: Resume
        href: Resume_Vishruth.pdf
  page-footer:
    left: Copyright 2024, Vishruth Veerendranath
    right: This website was made with &#10084; using <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    # link-external-icon: true
    # link-external-newwindow: true
    from: markdown+emoji
    theme: cosmo
    css: styles.scss