project:
  type: website
  output-dir: docs

website:
  title: "Vishruth Veerendranath"
  favicon: profile.png
  navbar:
    background: primary
    right:
      - publications.qmd
      - experience.qmd
      - text: Resume
        href: Resume_Vishruth.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
