project:
  type: website
  output-dir: docs

website:
  title: "Vishruth Veerendranath"
  navbar:
    background: primary
    right:
      - publications.qmd
      - experience.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
